### ISSUE TITLE
Faster Response time when firing buster gun

### ISSUE THREAD

**Issue by JJChalupnik** [DamnedNForsaken/MMLX#160]
currently, if the player left-clicks the mouse or hits the fire button on a gamepad, Megaman doesn't get off a shot. You actually have to hold it down to fire the first shot. This should be remedied as the first button press is very important to feeling snappy and polished. He should be able to respond quickly and fire the buster gun at near the moment of button press. Followed by the subsequent timed firing based off the "Rapid" stat. Let me know if this makes sense or not and I will do better to explain.

**Comment by DamnedNForsaken** [comment]
@JJChalupnik this was by design. Siph changed the firing mechanics because... well i forget now. But switching this back to the other way/ improving this etc.. is going to take some work FYI. I think that we are on the same page.... need to test quite a bit too on this to fine the happy medium of what works and doesn't. I love alot of how smooth it is now.. but yes i do agree that it needs to be more snappy.

**Comment by JJChalupnik** [comment]
The work Siph did is great. There is a lot working with what he has built, so in no way am i suggesting we revert.  I'm only talking about that delay between the player pressing the button and Megaman firing. (Same issue with the jump) We have to cut the head off the animation blend to ensure snappy player response. I don't want to rebuild all the goodness that he already put into it. Most of it is solid. We just need to refine it.

**Comment by DamnedNForsaken** [comment]
@JJChalupnik Making sure we are on the same page of this....
i.e. as is now you must hold the fire button to actually fire that first shot.
1) Either we change the mechanic of the first shot to be just click and it will raise and fire....
2) Or we speed up that first shot so that you still have to hold it down to fire but will get the first one off much quicker.

Either we do one or two

**Comment by JJChalupnik** [comment]
Yup. Same page. I suggest we do 2. Cut the head off the anim montage so that the first shot happens at click or button press. That first shot is really important for the player to have agency. I think everything else is working extremely well. We only really need 1 - 2 frames of his anticipation before firing. It can happen fast. The overlapping action after he fires is what sells it. Does that make sense?

**Comment by JJChalupnik** [comment]
- Still need that first shot delay to be reduced to near instantaneous. So if the player can fire (Rapid + Energy stats), then let that first shot fire quickly if Megaman is in idle. It will really help make him feel more responsive and snappy.

**Comment by JJChalupnik** [comment]
Fixed. May revisit aspects of this but it is much much much better now.
