### ISSUE TITLE
Need Recoil, damage, and Scale adjustments for Charge shot

### ISSUE THREAD

**Issue by JJChalupnik** [DamnedNForsaken/MMLX#169]
The new charge shot is AMAZING. I'd like to run this by you as a few enhancements to this new feature. One, we need real recoil when he fires. Playing the recoil anim as well as physically pushing megaman back would be very cool to see. It would also be nice to see the scale of the fireball larger after it is fired, as well as making it do significantly more damage. 

Might also be nice if it doesn't stop after hitting a target, it just goes through them, or perhaps breaks up into smaller fireballs.

**Comment by DamnedNForsaken** [comment]
@JJChalupnik 
A couple of thoughts on this:
So i have scaled the shot to be twice the size of the original shot, do you want it to be bigger. IDC just asking.
Regarding the recoil, this is a fine line.... I.e. Siph's thoughts were that if we have to much recoil we take away from player control... i.e. every 1/2 second that we prevent the player from moving affects gameplay.
I have adjusted it way down, due to this concept. I think that we can fine tune it more to have alil more recoil and ascetic.. but indeed we have a fine line to tread here.

Regarding how the Charged shot affects the world. I like the idea of it going through multiple enemies... I think that we should also find a different particle effect for the charge shot too, i.e. at least add alittle more flare to it

**Comment by JJChalupnik** [comment]
Yes I agree the vfx particles need to change at some point but for now i think a scaling of the fired plasma will do. It should be huge IMO. Like almost as tall as Megaman lol. I'm just curious if it would look good. 

As for the charge shot recoil. Personally, I think we should make him vulnerable after firing. Its part of what adds to the challenge of the game, and the risk the player takes to use the shot in the first place. Plus all that power needs a kind of recoil to balance it out. It can even be a stat that can be reduced at some point, so there's less recoil or smaller cool-down. That's my 2-cents. What do you think?

**Comment by DamnedNForsaken** [comment]
@JJChalupnik
I think at some point this has been adjusted and is good enough, what do you think? can i close this

**Comment by JJChalupnik** [comment]
Yeah we can close it for now. There's gonna be a layer of polish we can do later that will basically address it when the time comes.
