### ISSUE TITLE
Issues with targetting

### ISSUE THREAD

**Issue by DamnedNForsaken** [DamnedNForsaken/MMLX#5]
Error messages are reported for the dynamic targeting plugin.
Not sure on more of this but there is pending kill calls for enemies that are not being able to be executed

**Comment by DamnedNForsaken** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [[MMLX -22] Investigate the issue with targeting that causes errors.](https://trello.com/c/LTbG9kS2/24-mmlx-22-investigate-the-issue-with-targeting-that-causes-errors)

**Comment by DamnedNForsaken** [comment]
Another issue i see with targeting, though it just may be my bad eyes is that the when far away the target reticles seem to be too low on the z-axis, when you get close of course they update higher along the axis to the proper spot, but when far away they are too low.

**Comment by DamnedNForsaken** [comment]
Well i have a fix in... I don't like how I did it, but it makes sense giving my limited understanding on this whole of the eco system... I.e. i believe that this might cause us issues in the future.
Essentially I added `is valid` checks within the dynamic targeting scripting. I mean i don't know why the author is not checking for this thing.

Regardless, this has removed the errors and makes some logical sense.
There is a bigger issue in the whole of the targeting however.

**Comment by JJChalupnik** [comment]
This issue is still pretty prevalent. The dynamic targeting plugin works pretty well, but if you want to integrate your own then by all means. Here is a list of issues I see out the gate:

- Targeting appears to lock on to pivot, or some lower point on a mesh target. Needs to move higher to the bounding box center of the targeted mesh.

- Has issues with locking on and off. Not sure what is causing the bug. I thought i had this fixed on my version before we did the big merge. But basically if you lock and unlock quickly, or try to kick while locked on, or do other things it breaks

- Aim offsets dont go far enough to fire at targets past their aim range, so when MM's arm will aim one direction, while firing in another, particularly when the camera is behind aiming behind MM's orientation.  This can be solved by either adding 360 degrees of aiming in the aim offsets, or by forcing megaman to no longer aim his buster gun when the camera is aiming behind him. Or a combo of both.

General bugginess when working. seems unstable on when it fails and when it works.

This feature as of now is still very broken.

**Comment by JJChalupnik** [comment]
Thanks for fixing the offset thing. That was driving me nuts. 

I noticed something odd about the targeting. We need a check to see if no targets are available, and then allow it to resume its normal functioning.

Basically if you launch the game, and the first thing you do is attempt to lock on, but no target is available, megaman will 'lock' his orientation, and he will basically be broken for the remaining of the play session. But the moment you do lockon and actually find a target when you first launch, it appears to work after that, even if you don't have a target available later. 

You can replicate this by dropping Megaman into an empty map and then trying to lockon with him. It should break it.

**Comment by DamnedNForsaken** [comment]
This really should have been broken up into several issues...
But hindsight is 20/20...
Working towards this... besides the build errors this is probably the biggest bug in my opinion.

**Comment by DamnedNForsaken** [comment]
So I have fixed the major issues with the targeting I feel.
* The offset, was fixed a PR or two ago... not going to find reference feeling lazy... (but the conclusion was that due to the target widget being defined as a square or so, that .5,.5 was actually dead center as far as orientation is concerned.
* Fixed the kicking issue:
![image](https://user-images.githubusercontent.com/6027892/59152146-5281f500-8a0c-11e9-91c3-71a11d22077c.png)
Basically we had this disabled at some point, probably during a debug of something else
* Fixed the aim offset when nothing is there issue, had to essentially add a check against the dynamic component because the check to see if targeting was giving false positives due to the logic etc...

Going to close this up now because i am going to push a PR up in a few minutes that should make all this go away... and any new issues, lets please create a ticket for (maybe more than one ticket because this ticket was way to big)
Yay thorn in my side gone!!
